'use client';
import { useState } from 'react';
import { PageHead } from '../portal';
import { useAuth } from '../providers';
import { Badge, Btn, Check, ErrorNote, Input, Modal, Select, Spinner, Stars, Table, Tabs, Textarea, useToast } from '../ui';
import { post, put } from '@/lib/api';
import { useApi } from '@/hooks/useApi';
import { date, label } from '@/lib/format';

const DIETARY = ['Halal', 'Vegan', 'Vegetarian', 'Gluten-free', 'Dairy-free', 'Nut-free'];
export function AdminCatalog() {
  const { can } = useAuth(); const toast = useToast(); const [tab, setTab] = useState('products'); const [status, setStatus] = useState(''); const [q, setQ] = useState('');
  const prods = useApi<any>(`/admin/products?limit=60${status ? `&status=${status}` : ''}${q ? `&q=${encodeURIComponent(q)}` : ''}`); const cats = useApi<any>('/admin/categories'); const revs = useApi<any>(tab === 'reviews' ? '/admin/reviews?status=' : null);
  const [p, setP] = useState<any>(null); const [verified, setVerified] = useState<string[]>([]); const [c, setC] = useState<any>(null); const [reason, setReason] = useState('');
  return (
    <>
      <PageHead title="Catalogue and reviews" />
      <Tabs value={tab} onChange={setTab} tabs={[{ key: 'products', label: 'Products' }, { key: 'categories', label: 'Categories' }, { key: 'reviews', label: 'Review moderation' }]} />
      {tab === 'products' && (<>
        <div className="row wrap-row" style={{ alignItems: 'flex-end', marginBottom: 12 }}><div style={{ minWidth: 240 }}><Input label="Search products" value={q} onChange={setQ} /></div><div style={{ width: 170 }}><Select label="Status" value={status} onChange={setStatus} options={['draft', 'active', 'archived']} placeholder="All" /></div></div>
        <ErrorNote error={prods.error} retry={prods.reload} />
        <Table caption="Products" rows={prods.data?.products ?? []} onRow={(r: any) => { setP(r); setVerified(r.dietary_verified ?? []); setReason(''); }} cols={[{ key: 'name', header: 'Product', render: (r: any) => <b>{r.name}</b> }, { key: 'vendor', header: 'Seller' }, { key: 'product_type', header: 'Type', render: (r: any) => label(r.product_type) }, { key: 'status', header: 'Status', render: (r: any) => <Badge status={r.status} /> }, { key: 'dietary', header: 'Dietary claims', render: (r: any) => <span className="small">{(r.dietary ?? []).map((d: string) => `${d}${r.dietary_verified?.includes(d) ? ' (verified)' : ''}`).join(', ')}</span> }, { key: 'updated_at', header: 'Updated', render: (r: any) => date(r.updated_at) }]} /></>)}
      {tab === 'categories' && (<>
        {can('catalog.manage') && <div style={{ marginBottom: 12 }}><Btn variant="primary" onClick={() => setC({ name: '', parent_id: '', description: '', is_active: true, position: 0 })}>Add category</Btn></div>}
        <Table caption="Categories" rows={cats.data?.categories ?? []} onRow={(r: any) => can('catalog.manage') && setC({ ...r, parent_id: r.parent_id ?? '', description: r.description ?? '' })} cols={[{ key: 'name', header: 'Category', render: (r: any) => <span>{r.parent_id ? '↳ ' : ''}<b>{r.name}</b></span> }, { key: 'slug', header: 'URL', render: (r: any) => <code>/c/{r.slug}</code> }, { key: 'is_active', header: 'Status', render: (r: any) => <Badge tone={r.is_active ? 'ok' : ''}>{r.is_active ? 'Active' : 'Hidden'}</Badge> }]} /></>)}
      {tab === 'reviews' && <Table caption="Reviews" rows={revs.data?.reviews ?? []} cols={[{ key: 'rating', header: 'Rating', render: (r: any) => <Stars value={r.rating} /> }, { key: 'body', header: 'Review', render: (r: any) => <span className="small">{r.body}</span> }, { key: 'subject_type', header: 'About', render: (r: any) => label(r.subject_type) }, { key: 'status', header: 'Status', render: (r: any) => <Badge status={r.status} /> }, { key: 'x', header: '', render: (r: any) => can('reviews.moderate') ? <span className="row">{r.status !== 'hidden' && <Btn size="sm" variant="danger-outline" onClick={async () => { await post(`/admin/reviews/${r.id}/moderate`, { status: 'hidden', note: 'Hidden by moderator' }); toast('Hidden'); revs.reload(); }}>Hide</Btn>}{r.status !== 'published' && <Btn size="sm" variant="secondary" onClick={async () => { await post(`/admin/reviews/${r.id}/moderate`, { status: 'published' }); toast('Published'); revs.reload(); }}>Publish</Btn>}</span> : null }]} />}
      {p && <Modal title={p.name} onClose={() => setP(null)} footer={can('catalog.manage') ? <><Btn variant="secondary" onClick={async () => { await post(`/admin/products/${p.id}/verify-dietary`, { verified }); toast('Dietary verification saved'); setP(null); prods.reload(); }}>Save dietary verification</Btn>{p.status === 'active' ? <Btn variant="danger" onClick={async () => { await post(`/admin/products/${p.id}/status`, { status: 'archived', reason: reason || 'Removed by moderator' }); toast('Removed from the shop'); setP(null); prods.reload(); }}>Remove from shop</Btn> : <Btn variant="leaf" onClick={async () => { await post(`/admin/products/${p.id}/status`, { status: 'active', reason }); toast('Published'); setP(null); prods.reload(); }}>Publish</Btn>}</> : undefined}>
        <div className="stack"><p className="small muted">{p.vendor} · {label(p.product_type)}</p><fieldset><legend>Verified dietary claims</legend><div className="row wrap-row">{DIETARY.filter((d) => (p.dietary ?? []).includes(d)).map((d) => <Check key={d} label={d} checked={verified.includes(d)} onChange={(v) => setVerified((a) => (v ? [...a, d] : a.filter((x) => x !== d)))} />)}{!(p.dietary ?? []).length && <span className="muted">The seller made no dietary claims.</span>}</div><p className="hint">Only mark a claim as verified after checking the ingredients or certification.</p></fieldset><Textarea label="Reason for status change" value={reason} onChange={setReason} optional /></div></Modal>}
      {c && <Modal title={c.id ? 'Edit category' : 'New category'} onClose={() => setC(null)} footer={<><Btn variant="secondary" onClick={() => setC(null)}>Cancel</Btn><Btn variant="primary" onClick={async () => { try { const b = { name: c.name, parent_id: c.parent_id || null, description: c.description || undefined, is_active: !!c.is_active, position: Number(c.position) || 0 }; if (c.id) await put(`/admin/categories/${c.id}`, b); else await post('/admin/categories', b); toast('Category saved'); setC(null); cats.reload(); } catch (e: any) { toast(e.message, 'bad'); } }}>Save</Btn></>}>
        <div className="form-grid"><Input label="Name" value={c.name} onChange={(v) => setC({ ...c, name: v })} /><Select label="Parent" value={c.parent_id} onChange={(v) => setC({ ...c, parent_id: v })} options={(cats.data?.categories ?? []).filter((x: any) => !x.parent_id && x.id !== c.id).map((x: any) => ({ value: x.id, label: x.name }))} placeholder="Top level" /><Textarea label="Description" value={c.description} onChange={(v) => setC({ ...c, description: v })} full optional /><Input label="Sort position" type="number" value={c.position} onChange={(v) => setC({ ...c, position: v })} /><Check label="Visible in the shop" checked={!!c.is_active} onChange={(v) => setC({ ...c, is_active: v })} /></div></Modal>}
      <span className="sr-only">{prods.loading ? <Spinner /> : null}</span>
    </>
  );
}
