'use client';
import { useState } from 'react';
import { PageHead } from '../portal';
import { useAuth } from '../providers';
import { Badge, Btn, Check, ErrorNote, Input, KV, Modal, Pager, Select, Spinner, Stat, Table, Tabs, Textarea, useToast } from '../ui';
import { get, post } from '@/lib/api';
import { useApi } from '@/hooks/useApi';
import { date, dateTime, label, money } from '@/lib/format';

export function AdminFinance() {
  const { can } = useAuth(); const toast = useToast(); const [tab, setTab] = useState('summary');
  const sum = useApi<any>('/admin/finance/summary'); const pays = useApi<any>(tab === 'payments' ? '/admin/finance/payments' : null); const refunds = useApi<any>(tab === 'refunds' ? '/admin/finance/refunds' : null);
  const [pstatus, setPstatus] = useState(''); const [ptype, setPtype] = useState(''); const payouts = useApi<any>(tab === 'payouts' ? `/admin/finance/payouts?${pstatus ? `status=${pstatus}&` : ''}${ptype ? `type=${ptype}` : ''}` : null, [pstatus, ptype]);
  const [lpage, setLpage] = useState(1); const ledger = useApi<any>(tab === 'ledger' ? `/admin/finance/ledger?page=${lpage}&limit=50` : null);
  const [po, setPo] = useState<any>(null); const [act, setAct] = useState<null | { kind: string; p: any }>(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false);
  const s = sum.data; const rec = s?.reconciliation;
  const run = async (fn: () => Promise<any>, msg: string) => { setBusy(true); try { await fn(); toast(msg); setAct(null); setReason(''); payouts.reload(); sum.reload(); } catch (e: any) { toast(e.message, 'bad'); } finally { setBusy(false); } };
  return (
    <>
      <PageHead title="Finance and payouts" sub="Every figure is read from the append-only ledger." actions={can('payouts.manage') && <Btn variant="primary" busy={busy} onClick={() => run(() => post('/admin/finance/payouts/run', { process: false }), 'Payout run created for review')}>Create payout run</Btn>} />
      <Tabs value={tab} onChange={setTab} tabs={[{ key: 'summary', label: 'Summary and reconciliation' }, { key: 'payouts', label: 'Payouts' }, { key: 'payments', label: 'Payments' }, { key: 'refunds', label: 'Refunds' }, { key: 'ledger', label: 'Ledger' }]} />
      {tab === 'summary' && (!s ? <Spinner /> : (<div className="stack" style={{ '--gap': '18px' } as any}>
        <div className={`alert ${s.trial_balance.balanced && rec?.balanced ? 'ok' : 'bad'}`} role="status"><b>{s.trial_balance.balanced ? 'Ledger is balanced' : 'LEDGER DOES NOT BALANCE'}.</b> Debits {money(s.trial_balance.totals.debit)} equal credits {money(s.trial_balance.totals.credit)}. {rec && <>Payments reconciliation: {rec.balanced ? 'no differences' : 'differences found'}.</>}</div>
        <div className="grid cols-4">{[['Commission revenue', 'revenue_commission'], ['Delivery revenue', 'revenue_delivery'], ['Service fee revenue', 'revenue_service_fee'], ['Owed to vendors', 'liability_vendor'], ['Owed to drivers', 'liability_driver'], ['Tax collected', 'liability_tax'], ['Driver pay expense', 'expense_driver_pay'], ['Promotion cost', 'expense_promo']].map(([l, a]) => { const acc = s.trial_balance.accounts.find((x: any) => x.account === a); return <Stat key={a} label={l} value={money(Math.abs(acc?.balance ?? 0))} />; })}</div>
        <section><h2 style={{ fontSize: '1.15rem' }}>Trial balance</h2><Table caption="Trial balance" rows={s.trial_balance.accounts.map((a: any) => ({ ...a, id: a.account }))} cols={[{ key: 'account', header: 'Account', render: (a: any) => label(a.account) }, { key: 'debit', header: 'Debits', align: 'right', render: (a: any) => money(a.debit) }, { key: 'credit', header: 'Credits', align: 'right', render: (a: any) => money(a.credit) }, { key: 'balance', header: 'Balance', align: 'right', render: (a: any) => money(a.balance) }]} /></section>
        {rec && !rec.balanced && <pre className="json">{JSON.stringify(rec, null, 2)}</pre>}
      </div>))}
      {tab === 'payouts' && (<>
        <div className="row wrap-row" style={{ marginBottom: 12 }}><div style={{ width: 170 }}><Select label="Status" value={pstatus} onChange={setPstatus} options={['pending', 'processing', 'paid', 'held', 'failed', 'reversed']} placeholder="All" /></div><div style={{ width: 150 }}><Select label="Payee" value={ptype} onChange={setPtype} options={['vendor', 'driver']} placeholder="All" /></div></div>
        <ErrorNote error={payouts.error} retry={payouts.reload} />
        <Table caption="Payouts" rows={payouts.data?.payouts ?? []} onRow={async (r: any) => setPo(await get(`/admin/finance/payouts/${r.id}`))} cols={[{ key: 'payee_name', header: 'Payee', render: (r: any) => <span>{r.payee_name ?? r.payee_id.slice(0, 8)}<div className="tiny muted">{label(r.payee_type)}</div></span> }, { key: 'period', header: 'Period', render: (r: any) => `${date(r.period_start)} to ${date(r.period_end)}` }, { key: 'gross', header: 'Gross', align: 'right', render: (r: any) => money(r.gross) }, { key: 'commission', header: 'Commission', align: 'right', render: (r: any) => money(r.commission) }, { key: 'refunds', header: 'Refunds', align: 'right', render: (r: any) => money(r.refunds) }, { key: 'net', header: 'Net', align: 'right', render: (r: any) => <b>{money(r.net)}</b> }, { key: 'status', header: 'Status', render: (r: any) => <><Badge status={r.status} />{r.hold_reason && <div className="tiny muted">{r.hold_reason}</div>}</> }, { key: 'x', header: '', render: (r: any) => can('payouts.manage') ? <span className="row" onClick={(e) => e.stopPropagation()}>{r.status === 'pending' && <Btn size="sm" variant="leaf" onClick={() => run(() => post(`/admin/finance/payouts/${r.id}/process`), 'Payout processed')}>Pay</Btn>}{['pending', 'failed'].includes(r.status) && <Btn size="sm" variant="secondary" onClick={() => setAct({ kind: 'hold', p: r })}>Hold</Btn>}{r.status === 'held' && <Btn size="sm" variant="secondary" onClick={() => run(() => post(`/admin/finance/payouts/${r.id}/release`), 'Released')}>Release</Btn>}{r.status === 'paid' && <Btn size="sm" variant="danger-outline" onClick={() => setAct({ kind: 'reverse', p: r })}>Reverse</Btn>}</span> : null }]} /></>)}
      {tab === 'payments' && <Table caption="Payments" rows={pays.data?.payments ?? []} cols={[{ key: 'order_number', header: 'Order', render: (r: any) => r.number ?? r.order_id.slice(0, 8) }, { key: 'provider', header: 'Provider' }, { key: 'card', header: 'Card', render: (r: any) => (r.card_brand ? `${r.card_brand} ${r.card_last4}` : '') }, { key: 'status', header: 'Status', render: (r: any) => <Badge status={r.status} /> }, { key: 'amount', header: 'Amount', align: 'right', render: (r: any) => money(r.amount) }, { key: 'refunded_amount', header: 'Refunded', align: 'right', render: (r: any) => money(r.refunded_amount) }, { key: 'failure_internal', header: 'Failure (internal)', render: (r: any) => <span className="small">{r.failure_internal ?? ''}</span> }, { key: 'captured_at', header: 'Captured', render: (r: any) => (r.captured_at ? dateTime(r.captured_at) : '') }]} />}
      {tab === 'refunds' && <Table caption="Refunds" rows={refunds.data?.refunds ?? []} cols={[{ key: 'created_at', header: 'When', render: (r: any) => dateTime(r.created_at) }, { key: 'order_number', header: 'Order' }, { key: 'amount', header: 'Amount', align: 'right', render: (r: any) => money(r.amount) }, { key: 'bearer', header: 'Cost borne by', render: (r: any) => label(r.bearer) }, { key: 'reason', header: 'Reason' }, { key: 'status', header: 'Status', render: (r: any) => <Badge status={r.status} /> }]} />}
      {tab === 'ledger' && (<><Table caption="Ledger" rows={ledger.data?.entries ?? []} cols={[{ key: 'id', header: '#' }, { key: 'created_at', header: 'When', render: (r: any) => dateTime(r.created_at) }, { key: 'account', header: 'Account', render: (r: any) => label(r.account) }, { key: 'entry_type', header: 'Type', render: (r: any) => label(r.entry_type) }, { key: 'order_number', header: 'Order' }, { key: 'debit', header: 'Debit', align: 'right', render: (r: any) => (r.debit ? money(r.debit) : '') }, { key: 'credit', header: 'Credit', align: 'right', render: (r: any) => (r.credit ? money(r.credit) : '') }]} /><Pager page={lpage} pages={ledger.data?.entries?.length === 50 ? lpage + 1 : lpage} onPage={setLpage} /><p className="hint">Ledger rows can never be edited or deleted. Mistakes are fixed with new reversing entries.</p></>)}
      {po && <Modal title="Payout statement" onClose={() => setPo(null)} wide><KV items={[['Payee', po.payee], ['Status', label(po.payout.status)], ['Gross', money(po.payout.gross)], ['Commission', money(po.payout.commission)], ['Refunds', money(po.payout.refunds)], ['Adjustments', money(po.payout.adjustments)], ['Net', money(po.payout.net)], ['Provider reference', po.payout.provider_ref]]} /><Table caption="Lines" rows={po.items ?? []} cols={[{ key: 'description', header: 'Line' }, { key: 'gross', header: 'Gross', align: 'right', render: (r: any) => money(r.gross) }, { key: 'commission', header: 'Commission', align: 'right', render: (r: any) => money(r.commission) }, { key: 'refunds', header: 'Refunds', align: 'right', render: (r: any) => money(r.refunds) }, { key: 'net', header: 'Net', align: 'right', render: (r: any) => money(r.net) }]} /></Modal>}
      {act && <Modal title={act.kind === 'hold' ? 'Hold this payout' : 'Reverse this payout'} onClose={() => setAct(null)} footer={<><Btn variant="secondary" onClick={() => setAct(null)}>Back</Btn><Btn variant="danger" busy={busy} disabled={reason.length < 3} onClick={() => run(() => post(`/admin/finance/payouts/${act.p.id}/${act.kind}`, { reason }), act.kind === 'hold' ? 'Held' : 'Reversed')}>Confirm</Btn></>}><Textarea label="Reason (audit log)" value={reason} onChange={setReason} />{act.kind === 'reverse' && <p className="hint">The ledger is reversed with new entries and the amount is carried forward to the next payout.</p>}</Modal>}
    </>
  );
}
void Check; void Input;
