// Demo catalog for the seed. All businesses, people and products here are fictional.
export type PT = 'dry' | 'fresh' | 'frozen' | 'prepared' | 'chef_meal';
export interface SeedProduct {
  name: string; cat: string; type: PT; img: string; cuisine?: string; country?: string; brand?: string; desc: string; tax?: string;
  variants: [name: string, price: number, stock: number, sale?: number][]; weight?: number; prep?: number; allergens?: string[]; dietary?: string[];
  tags?: string[]; shelf?: number; storage?: string; ingredients?: string; cap?: number; unit?: string; popular?: number;
}
export interface SeedVendor {
  key: string; type: 'grocery' | 'specialty' | 'prepared' | 'chef'; trading: string; legal: string; desc: string; email: string; phone: string; owner: string;
  line1: string; city: string; region: string; postal: string; cuisines: string[]; prep: number; minOrder: number; status: 'approved' | 'submitted' | 'draft' | 'suspended' | 'under_review';
  ownDelivery?: boolean; pickup?: boolean; chef?: { display: string; bio: string; specialties: string[]; daily: number; hourly?: number; days: number[] }; products: SeedProduct[]; hours?: [string, string];
  commission?: number; logo?: string; cover?: string;
}

export const CATEGORIES: { slug: string; name: string; parent?: string; desc: string; img: string }[] = [
  { slug: 'pantry', name: 'Pantry', desc: 'Grains, flours, beans, oils and cooking essentials.', img: 'grains' },
  { slug: 'rice-grains', name: 'Rice and grains', parent: 'pantry', desc: 'Rice, fonio, couscous and whole grains.', img: 'grains' },
  { slug: 'flours-swallow', name: 'Flours and swallow', parent: 'pantry', desc: 'Garri, yam flour, teff and more.', img: 'flour' },
  { slug: 'beans-legumes', name: 'Beans and legumes', parent: 'pantry', desc: 'Honey beans, black eyed peas and lentils.', img: 'beans' },
  { slug: 'spices-seasonings', name: 'Spices and seasonings', parent: 'pantry', desc: 'Blends, peppers and seasonings from across the continent.', img: 'spices' },
  { slug: 'oils-sauces', name: 'Oils and sauces', parent: 'pantry', desc: 'Palm oil, shito, pepper sauces and ghee.', img: 'oil' },
  { slug: 'canned-packaged', name: 'Canned and packaged', parent: 'pantry', desc: 'Ackee, callaloo, tomato paste and ready staples.', img: 'canned' },
  { slug: 'snacks', name: 'Snacks', desc: 'Chin chin, plantain chips and sweet treats.', img: 'snacks' },
  { slug: 'drinks', name: 'Drinks', desc: 'Zobo, sorrel, ginger beer and coffee.', img: 'drinks' },
  { slug: 'fresh-produce', name: 'Fresh produce', desc: 'Plantain, yam, peppers, okra and leafy greens.', img: 'produce' },
  { slug: 'meat-poultry', name: 'Meat and poultry', desc: 'Goat, oxtail, lamb and chicken, including halal.', img: 'meat' },
  { slug: 'fish-seafood', name: 'Fish and seafood', desc: 'Tilapia, croaker, smoked and dried fish.', img: 'fish' },
  { slug: 'bakery', name: 'Bakery', desc: 'Hard dough bread, injera and pastries.', img: 'bakery' },
  { slug: 'prepared-meals', name: 'Prepared meals', desc: 'Ready to eat dishes from kitchens and chefs.', img: 'meal' },
];

export const VENDORS: SeedVendor[] = [
  {
    key: 'nkechi', type: 'grocery', trading: 'Mama Nkechi African Market', legal: 'Nkechi Foods Inc.', desc: 'A neighbourhood African grocery in Toronto stocking West African staples, fresh produce and frozen proteins since 2009.',
    email: 'orders@nkechi.demo.eazyfoods.test', phone: '416-555-0111', owner: 'Nkechi Adeyemi', line1: '1250 Dufferin Street', city: 'Toronto', region: 'ON', postal: 'M6H 4C4', cuisines: ['Nigerian', 'Ghanaian', 'West African'], prep: 15, minOrder: 15, status: 'approved', hours: ['08:00', '21:00'], logo: 'logo-nkechi', cover: 'cover-market',
    products: [
      { name: 'Ofada Rice', cat: 'rice-grains', type: 'dry', img: 'grains', cuisine: 'Nigerian', country: 'Nigeria', brand: 'Mama Gold', tax: 'zero_rated', popular: 40, desc: 'Unpolished local rice with a nutty aroma, traditionally served with ayamase stew. Stone picked and ready to cook.', variants: [['2 kg', 11.99, 60], ['5 kg', 26.99, 40], ['10 kg', 49.99, 18]], weight: 2000, shelf: 365, storage: 'Store in a cool dry place in a sealed container.', tags: ['rice', 'ofada', 'nigerian'] },
      { name: 'Long Grain Parboiled Rice', cat: 'rice-grains', type: 'dry', img: 'grains', cuisine: 'Nigerian', country: 'Nigeria', brand: 'Mama Gold', tax: 'zero_rated', popular: 65, desc: 'Parboiled long grain rice that stays separate and firm. The base for party jollof.', variants: [['5 kg', 18.99, 80], ['10 kg', 33.99, 55], ['25 kg', 74.99, 20, 69.99]], weight: 5000, shelf: 540, tags: ['rice', 'jollof'] },
      { name: 'White Garri (Ijebu)', cat: 'flours-swallow', type: 'dry', img: 'flour', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', popular: 50, desc: 'Crisp, sour Ijebu style garri made from fermented cassava. Soak with cold water or make eba.', variants: [['1 kg', 5.99, 100], ['2 kg', 10.99, 70], ['5 kg', 24.99, 30]], weight: 1000, shelf: 365, tags: ['garri', 'cassava', 'eba'] },
      { name: 'Yellow Garri', cat: 'flours-swallow', type: 'dry', img: 'flour', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', desc: 'Palm oil fried garri with a golden colour and rounded flavour.', variants: [['1 kg', 6.49, 60], ['2 kg', 11.99, 35]], weight: 1000, shelf: 365, tags: ['garri', 'cassava'] },
      { name: 'Pounded Yam Flour', cat: 'flours-swallow', type: 'dry', img: 'flour', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', popular: 30, desc: 'Instant pounded yam flour. Smooth, stretchy swallow in under five minutes.', variants: [['1.5 kg', 12.99, 45], ['4 kg', 29.99, 12]], weight: 1500, shelf: 365, tags: ['yam', 'swallow'] },
      { name: 'Honey Beans (Oloyin)', cat: 'beans-legumes', type: 'dry', img: 'beans', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', desc: 'Sweet brown beans for ewa agoyin, moi moi and porridge.', variants: [['1 kg', 6.99, 70], ['2 kg', 12.99, 40]], weight: 1000, shelf: 540, tags: ['beans', 'moimoi'] },
      { name: 'Black Eyed Peas', cat: 'beans-legumes', type: 'dry', img: 'beans', cuisine: 'West African', country: 'Nigeria', tax: 'zero_rated', desc: 'Clean, uniform black eyed peas for akara, waakye and stews.', variants: [['1 kg', 4.99, 90]], weight: 1000, shelf: 540, tags: ['beans', 'akara'] },
      { name: 'Red Palm Oil', cat: 'oils-sauces', type: 'dry', img: 'oil', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', popular: 38, desc: 'Unrefined red palm oil with a rich colour and flavour for stews and soups.', variants: [['500 ml', 7.99, 50], ['1 L', 13.99, 40], ['4 L', 46.99, 10]], weight: 500, shelf: 365, tags: ['palm oil', 'stew'] },
      { name: 'Ground Egusi (Melon Seeds)', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', popular: 28, desc: 'Freshly ground egusi for thick, nutty soups.', variants: [['250 g', 8.99, 55], ['500 g', 16.99, 30]], weight: 250, shelf: 180, allergens: ['seeds'], tags: ['egusi', 'soup'] },
      { name: 'Ground Crayfish', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', desc: 'Smoky ground crayfish to deepen soups, stews and jollof.', variants: [['100 g', 7.49, 60], ['250 g', 16.49, 24]], weight: 100, shelf: 270, allergens: ['shellfish'], tags: ['crayfish'] },
      { name: 'Suya Spice (Yaji)', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Nigerian', country: 'Nigeria', tax: 'standard', popular: 45, desc: 'Peanut and pepper rub for suya, grilled chicken and roasted plantain.', variants: [['100 g', 5.99, 80], ['250 g', 12.99, 36]], weight: 100, shelf: 365, allergens: ['peanuts'], dietary: ['Vegan'], tags: ['suya', 'yaji'] },
      { name: 'Seasoning Cubes (Chicken)', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'West African', country: 'Nigeria', tax: 'standard', desc: 'Pack of 24 bouillon cubes for everyday cooking.', variants: [['24 cubes', 4.49, 140]], weight: 240, shelf: 540, allergens: ['soy'], tags: ['seasoning'] },
      { name: 'Scotch Bonnet Peppers', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'West African', country: 'Canada', tax: 'zero_rated', desc: 'Fiery, fruity scotch bonnet peppers. Handle with gloves.', variants: [['250 g', 3.99, 40], ['500 g', 6.99, 25]], weight: 250, shelf: 7, storage: 'Refrigerate. Use within a week.', tags: ['pepper', 'ata rodo'] },
      { name: 'Green Plantain', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'West African', country: 'Ecuador', tax: 'zero_rated', popular: 22, desc: 'Firm green plantains for boiling, roasting or chips.', variants: [['Bunch of 4', 4.99, 45], ['Bunch of 8', 8.99, 25]], weight: 1200, shelf: 6, storage: 'Keep at room temperature.', tags: ['plantain'] },
      { name: 'Ripe Plantain (Dodo)', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'West African', country: 'Ecuador', tax: 'zero_rated', desc: 'Sweet, ripe plantains ready for frying.', variants: [['Bunch of 4', 5.49, 35]], weight: 1200, shelf: 4, tags: ['plantain', 'dodo'] },
      { name: 'Fresh Okra', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'West African', country: 'United States', tax: 'zero_rated', desc: 'Young tender okra for soups and stews.', variants: [['500 g', 5.99, 30]], weight: 500, shelf: 5, tags: ['okra'] },
      { name: 'Frozen Bitterleaf (Washed)', cat: 'fresh-produce', type: 'frozen', img: 'frozen', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', desc: 'Washed and ready bitterleaf for ofe onugbu and edikang ikong.', variants: [['300 g', 7.99, 24]], weight: 300, shelf: 365, storage: 'Keep frozen at -18 C.', tags: ['bitterleaf', 'soup'] },
      { name: 'Frozen Goat Meat (Cut)', cat: 'meat-poultry', type: 'frozen', img: 'meat', cuisine: 'West African', country: 'Canada', tax: 'zero_rated', popular: 26, desc: 'Bone in goat cut for pepper soup, stews and suya.', variants: [['1 kg', 17.99, 40], ['2 kg', 33.99, 18]], weight: 1000, shelf: 270, storage: 'Keep frozen at -18 C.', dietary: ['Halal'], tags: ['goat', 'meat'] },
      { name: 'Whole Tilapia (Cleaned)', cat: 'fish-seafood', type: 'frozen', img: 'fish', cuisine: 'West African', country: 'Ghana', tax: 'zero_rated', popular: 30, desc: 'Cleaned whole tilapia for grilling, banku pairing and pepper soup.', variants: [['1 kg (3 to 4 fish)', 12.99, 36]], weight: 1000, shelf: 270, storage: 'Keep frozen at -18 C.', allergens: ['fish'], tags: ['tilapia', 'fish'] },
      { name: 'Smoked Catfish', cat: 'fish-seafood', type: 'dry', img: 'fish', cuisine: 'Nigerian', country: 'Nigeria', tax: 'zero_rated', desc: 'Deeply smoked catfish for soups and sauces.', variants: [['300 g', 14.99, 20]], weight: 300, shelf: 180, allergens: ['fish'], tags: ['catfish', 'smoked'] },
      { name: 'Chin Chin (Crunchy)', cat: 'snacks', type: 'dry', img: 'snacks', cuisine: 'Nigerian', country: 'Nigeria', tax: 'standard', desc: 'Crunchy fried dough bites with nutmeg and vanilla.', variants: [['200 g', 5.49, 70], ['500 g', 11.99, 25]], weight: 200, shelf: 90, allergens: ['wheat', 'eggs', 'milk'], tags: ['snack', 'chinchin'] },
      { name: 'Plantain Chips (Salted)', cat: 'snacks', type: 'dry', img: 'snacks', cuisine: 'West African', country: 'Ghana', tax: 'standard', desc: 'Thin, crisp plantain chips lightly salted.', variants: [['150 g', 3.99, 90]], weight: 150, shelf: 120, dietary: ['Vegan', 'Gluten-free'], tags: ['snack', 'chips'] },
      { name: 'Zobo (Hibiscus Drink)', cat: 'drinks', type: 'fresh', img: 'drinks', cuisine: 'Nigerian', country: 'Canada', tax: 'standard', desc: 'House brewed hibiscus drink with ginger, cloves and pineapple.', variants: [['1 L', 6.99, 30]], weight: 1000, shelf: 5, storage: 'Keep refrigerated.', dietary: ['Vegan'], tags: ['zobo', 'hibiscus', 'drink'] },
    ],
  },
  {
    key: 'island', type: 'grocery', trading: 'Island Spice Caribbean Grocers', legal: 'Island Spice Foods Ltd.', desc: 'Jamaican, Trinidadian and Guyanese groceries, fresh hard dough bread and patties in Scarborough.',
    email: 'hello@islandspice.demo.eazyfoods.test', phone: '416-555-0142', owner: 'Marcus Campbell', line1: '2900 Kingston Road', city: 'Scarborough', region: 'ON', postal: 'M1P 3B4', cuisines: ['Jamaican', 'Caribbean'], prep: 15, minOrder: 20, status: 'approved', hours: ['09:00', '20:00'], logo: 'logo-island', cover: 'cover-market', commission: 10,
    products: [
      { name: 'Jerk Seasoning (Wet)', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Jamaican', country: 'Jamaica', brand: 'Island Spice', tax: 'standard', popular: 35, desc: 'Allspice, scotch bonnet and thyme jerk marinade. Medium heat.', variants: [['280 g', 6.99, 80], ['500 g', 11.99, 40]], weight: 280, shelf: 365, tags: ['jerk'] },
      { name: 'Ackee in Brine', cat: 'canned-packaged', type: 'dry', img: 'canned', cuisine: 'Jamaican', country: 'Jamaica', tax: 'zero_rated', desc: 'Canned ackee for the national breakfast with saltfish.', variants: [['540 ml tin', 9.99, 50]], weight: 540, shelf: 720, tags: ['ackee'] },
      { name: 'Callaloo in Brine', cat: 'canned-packaged', type: 'dry', img: 'canned', cuisine: 'Jamaican', country: 'Jamaica', tax: 'zero_rated', desc: 'Tender callaloo greens, ready to steam with onion and scotch bonnet.', variants: [['540 ml tin', 4.99, 60]], weight: 540, shelf: 720, tags: ['callaloo'] },
      { name: 'Salted Cod (Saltfish)', cat: 'fish-seafood', type: 'dry', img: 'fish', cuisine: 'Jamaican', country: 'Canada', tax: 'zero_rated', desc: 'Boneless salted cod. Soak overnight before cooking.', variants: [['454 g', 15.99, 30]], weight: 454, shelf: 365, allergens: ['fish'], tags: ['saltfish'] },
      { name: 'Frozen Oxtail', cat: 'meat-poultry', type: 'frozen', img: 'meat', cuisine: 'Jamaican', country: 'Canada', tax: 'zero_rated', popular: 33, desc: 'Meaty cut oxtail for slow braising.', variants: [['1 kg', 21.99, 28], ['2 kg', 41.99, 10]], weight: 1000, shelf: 270, storage: 'Keep frozen at -18 C.', tags: ['oxtail'] },
      { name: 'Beef Patties (Mild)', cat: 'prepared-meals', type: 'frozen', img: 'pastry', cuisine: 'Jamaican', country: 'Canada', tax: 'prepared', popular: 20, desc: 'Flaky turmeric pastry with seasoned beef. Pack of 6, heat from frozen.', variants: [['Pack of 6', 14.99, 36]], weight: 700, shelf: 180, storage: 'Keep frozen. Bake at 180 C for 25 minutes.', allergens: ['wheat', 'eggs'], tags: ['patty'] },
      { name: 'Hard Dough Bread', cat: 'bakery', type: 'fresh', img: 'bakery', cuisine: 'Jamaican', country: 'Canada', tax: 'zero_rated', desc: 'Baked this morning. Dense, slightly sweet and perfect for sandwiches.', variants: [['Large loaf', 5.49, 25]], weight: 680, shelf: 4, allergens: ['wheat', 'milk'], tags: ['bread'] },
      { name: 'Curry Powder (Jamaican Style)', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Jamaican', country: 'Jamaica', tax: 'standard', desc: 'Turmeric forward curry powder for goat, chicken and vegetables.', variants: [['227 g', 5.99, 70]], weight: 227, shelf: 540, dietary: ['Vegan'], tags: ['curry'] },
      { name: 'Gungo Peas', cat: 'beans-legumes', type: 'dry', img: 'beans', cuisine: 'Jamaican', country: 'Jamaica', tax: 'zero_rated', desc: 'Canned pigeon peas for rice and peas.', variants: [['540 ml tin', 3.99, 80]], weight: 540, shelf: 720, tags: ['peas'] },
      { name: 'Sorrel Drink Concentrate', cat: 'drinks', type: 'dry', img: 'drinks', cuisine: 'Caribbean', country: 'Jamaica', tax: 'standard', desc: 'Christmas season hibiscus and ginger concentrate. Dilute to taste.', variants: [['750 ml', 8.99, 30]], weight: 750, shelf: 270, dietary: ['Vegan'], tags: ['sorrel'] },
      { name: 'Ting Grapefruit Soda', cat: 'drinks', type: 'dry', img: 'drinks', cuisine: 'Jamaican', country: 'Jamaica', tax: 'standard', desc: 'Sparkling grapefruit soda. Six pack.', variants: [['6 x 330 ml', 8.49, 60]], weight: 2000, shelf: 365, tags: ['soda'] },
      { name: 'Yellow Yam', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'Jamaican', country: 'Jamaica', tax: 'zero_rated', desc: 'Starchy yellow yam, sold by the piece (about 1.5 kg).', variants: [['1 piece (about 1.5 kg)', 9.99, 22]], weight: 1500, shelf: 14, tags: ['yam'] },
      { name: 'Green Bananas', cat: 'fresh-produce', type: 'fresh', img: 'produce', cuisine: 'Jamaican', country: 'Ecuador', tax: 'zero_rated', desc: 'Firm green bananas for boiling with dumplings.', variants: [['Bunch of 6', 3.99, 40]], weight: 1000, shelf: 7, tags: ['banana'] },
    ],
  },
  {
    key: 'sahel', type: 'specialty', trading: 'Sahel Specialty Foods', legal: 'Sahel Specialty Foods Corp.', desc: 'Halal specialty foods from Ethiopia, Eritrea, Senegal and Somalia: spices, grains, injera and premium coffee.',
    email: 'team@sahel.demo.eazyfoods.test', phone: '905-555-0178', owner: 'Hana Tesfaye', line1: '3050 Hurontario Street', city: 'Mississauga', region: 'ON', postal: 'L5B 3B9', cuisines: ['Ethiopian', 'Senegalese', 'Somali'], prep: 20, minOrder: 25, status: 'approved', hours: ['10:00', '19:00'], logo: 'logo-sahel', cover: 'cover-spice',
    products: [
      { name: 'Berbere Spice Blend', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'standard', popular: 24, desc: 'Deep red chili blend with fenugreek, coriander and korarima. The soul of doro wat.', variants: [['100 g', 8.99, 60], ['250 g', 18.99, 30]], weight: 100, shelf: 365, dietary: ['Vegan', 'Halal'], tags: ['berbere'] },
      { name: 'Teff Flour (Ivory)', cat: 'flours-swallow', type: 'dry', img: 'flour', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'zero_rated', desc: 'Stoneground ivory teff for injera and porridge.', variants: [['1 kg', 11.99, 45], ['2 kg', 21.99, 22]], weight: 1000, shelf: 270, dietary: ['Vegan', 'Gluten-free'], tags: ['teff', 'injera'] },
      { name: 'Fresh Injera', cat: 'bakery', type: 'fresh', img: 'bakery', cuisine: 'Ethiopian', country: 'Canada', tax: 'zero_rated', popular: 27, desc: 'Soft, spongy teff injera made daily. Pack of 10.', variants: [['Pack of 10', 14.99, 18]], weight: 900, shelf: 4, storage: 'Keep sealed and refrigerate after opening.', dietary: ['Vegan'], tags: ['injera'] },
      { name: 'Niter Kibbeh (Spiced Butter)', cat: 'oils-sauces', type: 'dry', img: 'oil', cuisine: 'Ethiopian', country: 'Canada', tax: 'standard', desc: 'Clarified butter infused with cardamom, fenugreek and turmeric.', variants: [['250 g', 12.99, 25]], weight: 250, shelf: 180, allergens: ['milk'], dietary: ['Vegetarian'], tags: ['kibbeh'] },
      { name: 'Shiro Powder', cat: 'beans-legumes', type: 'dry', img: 'beans', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'zero_rated', desc: 'Seasoned chickpea flour for silky shiro wat.', variants: [['500 g', 9.99, 40]], weight: 500, shelf: 365, dietary: ['Vegan', 'Gluten-free'], tags: ['shiro'] },
      { name: 'Fonio Grain', cat: 'rice-grains', type: 'dry', img: 'grains', cuisine: 'Senegalese', country: 'Senegal', tax: 'zero_rated', desc: 'Ancient West African grain that cooks in five minutes.', variants: [['500 g', 12.99, 28]], weight: 500, shelf: 540, dietary: ['Vegan', 'Gluten-free'], tags: ['fonio'] },
      { name: 'Millet Couscous (Thiere)', cat: 'rice-grains', type: 'dry', img: 'grains', cuisine: 'Senegalese', country: 'Senegal', tax: 'zero_rated', desc: 'Hand rolled millet couscous for thiere and lakh.', variants: [['1 kg', 8.99, 32]], weight: 1000, shelf: 365, dietary: ['Vegan'], tags: ['couscous', 'millet'] },
      { name: 'Baobab Powder', cat: 'spices-seasonings', type: 'dry', img: 'spices', cuisine: 'Senegalese', country: 'Senegal', tax: 'standard', desc: 'Tangy baobab fruit powder for drinks and smoothies.', variants: [['200 g', 13.99, 20]], weight: 200, shelf: 540, dietary: ['Vegan'], tags: ['baobab'] },
      { name: 'Dried Hibiscus (Bissap)', cat: 'drinks', type: 'dry', img: 'drinks', cuisine: 'Senegalese', country: 'Senegal', tax: 'standard', desc: 'Whole dried hibiscus petals for bissap.', variants: [['100 g', 5.99, 55]], weight: 100, shelf: 540, dietary: ['Vegan'], tags: ['hibiscus', 'bissap'] },
      { name: 'Halal Lamb Shoulder (Frozen)', cat: 'meat-poultry', type: 'frozen', img: 'meat', cuisine: 'Somali', country: 'Canada', tax: 'zero_rated', popular: 18, desc: 'Halal certified lamb shoulder, bone in, cut for stews.', variants: [['1 kg', 24.99, 20], ['2 kg', 47.99, 8]], weight: 1000, shelf: 270, storage: 'Keep frozen at -18 C.', dietary: ['Halal'], tags: ['lamb'] },
      { name: 'Medjool Dates', cat: 'snacks', type: 'dry', img: 'snacks', cuisine: 'Somali', country: 'Jordan', tax: 'zero_rated', desc: 'Soft, caramel sweet dates.', variants: [['500 g', 14.99, 35]], weight: 500, shelf: 365, dietary: ['Vegan', 'Gluten-free'], tags: ['dates'] },
      { name: 'Ethiopian Yirgacheffe Coffee Beans', cat: 'drinks', type: 'dry', img: 'coffee', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'standard', popular: 21, desc: 'Floral, citrus bright light roast. Whole bean.', variants: [['340 g', 17.99, 40, 15.99]], weight: 340, shelf: 120, dietary: ['Vegan'], tags: ['coffee'] },
    ],
  },
  {
    key: 'lagos', type: 'prepared', trading: 'Lagos Kitchen', legal: 'Lagos Kitchen Hospitality Inc.', desc: 'Nigerian comfort food cooked fresh daily: party jollof, soups with swallow, suya, moi moi and puff puff. Catering trays for gatherings.',
    email: 'kitchen@lagoskitchen.demo.eazyfoods.test', phone: '416-555-0190', owner: 'Tunde Bakare', line1: '902 Queen Street West', city: 'Toronto', region: 'ON', postal: 'M6J 1G6', cuisines: ['Nigerian'], prep: 30, minOrder: 20, status: 'approved', hours: ['11:00', '22:00'], logo: 'logo-lagos', cover: 'cover-kitchen', ownDelivery: false,
    products: [
      { name: 'Party Jollof Rice with Chicken', cat: 'prepared-meals', type: 'prepared', img: 'meal', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', popular: 70, desc: 'Smoky firewood style jollof with grilled chicken, fried plantain and coleslaw.', variants: [['Regular', 17.99, 0], ['Family (serves 4)', 54.99, 0], ['Party (serves 8)', 99.0, 0]], prep: 30, allergens: ['eggs'], tags: ['jollof', 'chicken'], cap: 60 },
      { name: 'Egusi Soup with Pounded Yam', cat: 'prepared-meals', type: 'prepared', img: 'soup', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', popular: 44, desc: 'Rich melon seed soup with assorted meat and stockfish, served with smooth pounded yam.', variants: [['Regular', 19.99, 0], ['Family (serves 4)', 62.0, 0]], prep: 35, allergens: ['fish', 'shellfish', 'seeds'], tags: ['egusi', 'soup'], cap: 40 },
      { name: 'Beef Suya Skewers', cat: 'prepared-meals', type: 'prepared', img: 'grill', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', popular: 52, desc: 'Thin sliced beef rubbed with yaji, grilled over coals. Served with onions and tomato.', variants: [['5 skewers', 14.99, 0], ['10 skewers', 27.99, 0]], prep: 25, allergens: ['peanuts'], tags: ['suya', 'beef'], cap: 50 },
      { name: 'Moi Moi (Steamed Bean Pudding)', cat: 'prepared-meals', type: 'prepared', img: 'meal', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Pack of 3 silky bean puddings with egg and fish.', variants: [['Pack of 3', 9.99, 0]], prep: 20, allergens: ['eggs', 'fish'], dietary: ['Gluten-free'], tags: ['moimoi'], cap: 40 },
      { name: 'Puff Puff', cat: 'prepared-meals', type: 'prepared', img: 'pastry', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', popular: 36, desc: 'Golden fried dough balls, hot and lightly sweet.', variants: [['12 pieces', 7.99, 0], ['30 pieces', 17.99, 0]], prep: 15, allergens: ['wheat'], dietary: ['Vegetarian'], tags: ['puffpuff'], cap: 80 },
      { name: 'Nigerian Meat Pie (4 pack)', cat: 'prepared-meals', type: 'prepared', img: 'pastry', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Buttery pastry with minced beef, potato and carrot.', variants: [['4 pack', 12.99, 0]], prep: 20, allergens: ['wheat', 'milk', 'eggs'], tags: ['meatpie'], cap: 40 },
      { name: 'Fried Rice with Fried Plantain', cat: 'prepared-meals', type: 'prepared', img: 'meal', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Vegetable fried rice with liver, shrimp and sweet fried plantain.', variants: [['Regular', 16.99, 0], ['Family (serves 4)', 52.0, 0]], prep: 30, allergens: ['shellfish', 'soy'], tags: ['friedrice'], cap: 40 },
      { name: 'Jollof Catering Tray', cat: 'prepared-meals', type: 'prepared', img: 'platter', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Half pan party jollof for gatherings. Order at least 24 hours ahead.', variants: [['Serves 10', 85.0, 0], ['Serves 20', 160.0, 0]], prep: 120, allergens: ['eggs'], tags: ['catering'], cap: 6 },
    ],
  },
  {
    key: 'ada', type: 'chef', trading: "Chef Ada's Table", legal: 'Adaeze Obi', desc: 'Igbo home cooking with patience and pepper. Soups made from scratch in small batches in my Etobicoke kitchen.',
    email: 'ada@chef.demo.eazyfoods.test', phone: '416-555-0123', owner: 'Adaeze Obi', line1: '45 Burnhamthorpe Road', city: 'Etobicoke', region: 'ON', postal: 'M9W 5L5', cuisines: ['Nigerian', 'Igbo'], prep: 45, minOrder: 25, status: 'approved', pickup: true, logo: 'logo-chef-ada', cover: 'cover-kitchen',
    chef: { display: 'Chef Ada', bio: 'Adaeze learned to cook at her grandmother\'s fire in Enugu and now cooks traditional Igbo soups in Toronto. Everything is made to order in small batches.', specialties: ['Ofe Onugbu', 'Ofada and Ayamase', 'Pepper soup'], daily: 30, hourly: 10, days: [2, 3, 4, 5, 6, 0] },
    products: [
      { name: 'Ofe Onugbu (Bitterleaf Soup)', cat: 'prepared-meals', type: 'chef_meal', img: 'soup', cuisine: 'Igbo', country: 'Nigeria', tax: 'prepared', popular: 25, desc: 'Traditional bitterleaf soup thickened with cocoyam, with assorted meat and stockfish. Served with fufu.', variants: [['Regular', 21.0, 0], ['Family (serves 4)', 68.0, 0]], prep: 60, allergens: ['fish', 'shellfish'], tags: ['bitterleaf', 'soup'], cap: 15 },
      { name: 'Ofada Rice and Ayamase Stew', cat: 'prepared-meals', type: 'chef_meal', img: 'meal', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', popular: 31, desc: 'Ofada rice with green pepper designer stew, assorted meat and boiled egg.', variants: [['Regular', 19.5, 0], ['Family (serves 4)', 60.0, 0]], prep: 50, allergens: ['eggs'], tags: ['ofada', 'ayamase'], cap: 18 },
      { name: 'Goat Meat Pepper Soup', cat: 'prepared-meals', type: 'chef_meal', img: 'soup', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Peppery, aromatic goat meat soup with uda and uziza.', variants: [['Regular', 17.0, 0], ['Large', 29.0, 0]], prep: 45, dietary: ['Gluten-free'], tags: ['pepper soup', 'goat'], cap: 15 },
      { name: 'Akara (10 pieces)', cat: 'prepared-meals', type: 'chef_meal', img: 'pastry', cuisine: 'Nigerian', country: 'Nigeria', tax: 'prepared', desc: 'Crisp outside, fluffy inside bean fritters with pepper sauce.', variants: [['10 pieces', 8.5, 0]], prep: 25, dietary: ['Vegan', 'Gluten-free'], tags: ['akara'], cap: 25 },
    ],
  },
  {
    key: 'kofi', type: 'chef', trading: 'Chef Kofi Kitchen', legal: 'Kofi Asante', desc: 'Ghanaian street food and Sunday soups made with care in Brampton. Waakye, kelewele and light soup with fufu.',
    email: 'kofi@chef.demo.eazyfoods.test', phone: '905-555-0165', owner: 'Kofi Asante', line1: '120 Main Street North', city: 'Brampton', region: 'ON', postal: 'L6V 1N6', cuisines: ['Ghanaian'], prep: 40, minOrder: 20, status: 'approved', pickup: true, logo: 'logo-chef-kofi', cover: 'cover-kitchen',
    chef: { display: 'Chef Kofi', bio: 'Kofi spent ten years cooking in Kumasi before moving to Canada. His waakye is cooked with traditional millet leaf for colour and depth.', specialties: ['Waakye', 'Kelewele', 'Light soup'], daily: 25, hourly: 8, days: [1, 2, 3, 4, 5, 6] },
    products: [
      { name: 'Waakye with Fish and Shito', cat: 'prepared-meals', type: 'chef_meal', img: 'meal', cuisine: 'Ghanaian', country: 'Ghana', tax: 'prepared', popular: 29, desc: 'Rice and beans cooked with millet leaf, served with fried fish, gari, spaghetti, egg and homemade shito.', variants: [['Regular', 18.0, 0], ['Large', 26.0, 0]], prep: 40, allergens: ['fish', 'eggs', 'shellfish'], tags: ['waakye'], cap: 15 },
      { name: 'Kelewele (Spiced Fried Plantain)', cat: 'prepared-meals', type: 'chef_meal', img: 'snacks', cuisine: 'Ghanaian', country: 'Ghana', tax: 'prepared', desc: 'Ripe plantain cubes tossed in ginger, cayenne and cloves, fried until caramelised.', variants: [['Regular', 8.0, 0], ['Sharing', 14.0, 0]], prep: 20, dietary: ['Vegan', 'Gluten-free'], tags: ['kelewele'], cap: 25 },
      { name: 'Light Soup with Fufu', cat: 'prepared-meals', type: 'chef_meal', img: 'soup', cuisine: 'Ghanaian', country: 'Ghana', tax: 'prepared', desc: 'Clear tomato and pepper soup with goat meat, served with pounded cassava and plantain fufu.', variants: [['Regular', 20.0, 0], ['Family (serves 4)', 64.0, 0]], prep: 55, tags: ['light soup', 'fufu'], cap: 12 },
      { name: 'Banku with Grilled Tilapia', cat: 'prepared-meals', type: 'chef_meal', img: 'grill', cuisine: 'Ghanaian', country: 'Ghana', tax: 'prepared', popular: 23, desc: 'Fermented corn and cassava dough with whole grilled tilapia, pepper sauce and onions.', variants: [['Regular', 22.0, 0]], prep: 45, allergens: ['fish'], tags: ['banku', 'tilapia'], cap: 12 },
    ],
  },
  {
    key: 'selam', type: 'chef', trading: "Selam's Ethiopian Table", legal: 'Selam Bekele', desc: 'Ethiopian feasts, fasting platters and spiced coffee, cooked to order in Scarborough.',
    email: 'selam@chef.demo.eazyfoods.test', phone: '416-555-0188', owner: 'Selam Bekele', line1: '710 Lawrence Avenue East', city: 'Scarborough', region: 'ON', postal: 'M1K 4M2', cuisines: ['Ethiopian', 'Eritrean'], prep: 45, minOrder: 25, status: 'approved', pickup: true, logo: 'logo-chef-selam', cover: 'cover-spice',
    chef: { display: 'Chef Selam', bio: 'Selam cooks recipes from her mother\'s kitchen in Addis Ababa, with a strong vegan fasting menu. Injera is made fresh the same day.', specialties: ['Doro wat', 'Fasting platters', 'Coffee ceremony'], daily: 20, hourly: 6, days: [3, 4, 5, 6, 0] },
    products: [
      { name: 'Doro Wat with Injera', cat: 'prepared-meals', type: 'chef_meal', img: 'meal', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'prepared', popular: 34, desc: 'Slow cooked chicken in berbere and spiced butter with a boiled egg, served on fresh injera.', variants: [['Regular', 23.0, 0], ['Sharing (serves 2)', 42.0, 0]], prep: 60, allergens: ['eggs', 'milk', 'wheat'], dietary: ['Halal'], tags: ['doro wat'], cap: 10 },
      { name: 'Veggie Combo Platter (Vegan)', cat: 'prepared-meals', type: 'chef_meal', img: 'platter', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'prepared', popular: 28, desc: 'Misir wat, gomen, shiro, atkilt and tikil gomen on injera. Fully plant based.', variants: [['Regular', 19.0, 0], ['Sharing (serves 2)', 35.0, 0]], prep: 45, dietary: ['Vegan'], tags: ['vegan', 'fasting'], cap: 12 },
      { name: 'Misir Wat (Spicy Red Lentils)', cat: 'prepared-meals', type: 'chef_meal', img: 'meal', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'prepared', desc: 'Red lentils simmered in berbere with garlic and ginger.', variants: [['Regular', 14.0, 0]], prep: 35, dietary: ['Vegan', 'Gluten-free'], tags: ['lentils'], cap: 12 },
      { name: 'Spiced Ethiopian Coffee (Thermos)', cat: 'prepared-meals', type: 'chef_meal', img: 'coffee', cuisine: 'Ethiopian', country: 'Ethiopia', tax: 'prepared', desc: 'Freshly roasted and brewed coffee with cardamom, in a 1 litre thermos.', variants: [['1 L', 16.0, 0]], prep: 30, dietary: ['Vegan'], tags: ['coffee'], cap: 10 },
    ],
  },
  // Not yet live: used to demonstrate onboarding and review queues.
  { key: 'baobab', type: 'grocery', trading: 'Baobab Fresh Market', legal: 'Baobab Fresh Market Ltd.', desc: 'Family run produce and spice shop opening in Ajax.', email: 'info@baobab.demo.eazyfoods.test', phone: '905-555-0134', owner: 'Ama Owusu', line1: '100 Kingston Road East', city: 'Ajax', region: 'ON', postal: 'L1S 1C3', cuisines: ['Ghanaian'], prep: 20, minOrder: 15, status: 'submitted', products: [] },
  { key: 'rasta', type: 'prepared', trading: 'Rasta Pot Kitchen', legal: 'Rasta Pot Kitchen Inc.', desc: 'Caribbean takeout, application in progress.', email: 'hi@rastapot.demo.eazyfoods.test', phone: '416-555-0199', owner: 'Devon Clarke', line1: '55 Eglinton Avenue East', city: 'Toronto', region: 'ON', postal: 'M4P 1G8', cuisines: ['Jamaican'], prep: 25, minOrder: 20, status: 'draft', products: [] },
  { key: 'sahara', type: 'chef', trading: 'Sahara Supper Club', legal: 'Layla Hassan', desc: 'North African supper club. Account suspended pending a food safety review.', email: 'layla@chef.demo.eazyfoods.test', phone: '647-555-0156', owner: 'Layla Hassan', line1: '8 Dundas Street East', city: 'Toronto', region: 'ON', postal: 'M5B 2G9', cuisines: ['Moroccan'], prep: 40, minOrder: 25, status: 'suspended', chef: { display: 'Chef Layla', bio: 'North African tagines and couscous.', specialties: ['Tagine'], daily: 15, days: [5, 6] }, products: [] },
];

export const CUSTOMERS = [
  { name: 'Amara Okafor', email: 'amara@demo.eazyfoods.test', phone: '416-555-0201', line1: '88 Davenport Road', city: 'Toronto', postal: 'M5R 1H3', fsa: 'M4W', marketing: true },
  { name: 'David Mensah', email: 'david@demo.eazyfoods.test', phone: '905-555-0202', line1: '350 Burnhamthorpe Road West', city: 'Mississauga', postal: 'L5B 3Y3', fsa: 'L5B', marketing: true },
  { name: 'Fatou Diallo', email: 'fatou@demo.eazyfoods.test', phone: '416-555-0203', line1: '1500 Ellesmere Road', city: 'Scarborough', postal: 'M1P 2X4', fsa: 'M1P', marketing: false },
  { name: 'Chidi Eze', email: 'chidi@demo.eazyfoods.test', phone: '905-555-0204', line1: '25 Peel Centre Drive', city: 'Brampton', postal: 'L6T 3R5', fsa: 'L6T', marketing: true },
  { name: 'Marie-Claire Joseph', email: 'marieclaire@demo.eazyfoods.test', phone: '416-555-0205', line1: '5200 Yonge Street', city: 'North York', postal: 'M2N 5P6', fsa: 'M2N', marketing: true },
  { name: 'Kwame Boateng', email: 'kwame@demo.eazyfoods.test', phone: '416-555-0206', line1: '3 Dundas Street West', city: 'Etobicoke', postal: 'M9W 1A1', fsa: 'M9W', marketing: false },
];

export const DRIVERS = [
  { name: 'Samuel Adjei', email: 'samuel@driver.demo.eazyfoods.test', phone: '647-555-0301', vehicle: 'car' as const, make: 'Toyota', model: 'Corolla', plate: 'CBZK 482', status: 'approved', online: true, lat: 43.6769, lng: -79.4372, cold: true },
  { name: 'Yasmin Ali', email: 'yasmin@driver.demo.eazyfoods.test', phone: '647-555-0302', vehicle: 'ebike' as const, make: 'Rad', model: 'Power', plate: '', status: 'approved', online: true, lat: 43.6426, lng: -79.3871, cold: false },
  { name: 'Emeka Nwosu', email: 'emeka@driver.demo.eazyfoods.test', phone: '647-555-0303', vehicle: 'car' as const, make: 'Honda', model: 'Civic', plate: 'BXTL 937', status: 'approved', online: true, lat: 43.7576, lng: -79.2732, cold: true },
  { name: 'Grace Mutesi', email: 'grace@driver.demo.eazyfoods.test', phone: '647-555-0304', vehicle: 'van' as const, make: 'Ford', model: 'Transit Connect', plate: 'CPRM 205', status: 'approved', online: false, lat: 43.5890, lng: -79.6441, cold: true },
  { name: 'Tariq Hussain', email: 'tariq@driver.demo.eazyfoods.test', phone: '647-555-0305', vehicle: 'scooter' as const, make: 'Vespa', model: 'Primavera', plate: 'M7K 39A', status: 'approved', online: true, lat: 43.7701, lng: -79.4081, cold: false },
  { name: 'Lena Fofana', email: 'lena@driver.demo.eazyfoods.test', phone: '647-555-0306', vehicle: 'car' as const, make: 'Hyundai', model: 'Elantra', plate: 'BZTN 118', status: 'submitted', online: false, lat: 43.65, lng: -79.38, cold: false },
  { name: 'Paul Kamau', email: 'paul@driver.demo.eazyfoods.test', phone: '647-555-0307', vehicle: 'car' as const, make: 'Kia', model: 'Rio', plate: 'CFLM 760', status: 'suspended', online: false, lat: 43.7, lng: -79.4, cold: false },
];

export const STAFF = [
  { email: 'admin@demo.eazyfoods.test', name: 'Priya Raman (Super Admin)', role: 'super_admin' },
  { email: 'ops@demo.eazyfoods.test', name: 'Jordan Blake (Operations)', role: 'operations_admin' },
  { email: 'vendors@demo.eazyfoods.test', name: 'Nadia Hakim (Vendor Admin)', role: 'vendor_admin' },
  { email: 'support@demo.eazyfoods.test', name: 'Tomas Reyes (Support)', role: 'customer_support' },
  { email: 'finance@demo.eazyfoods.test', name: 'Helen Wu (Finance)', role: 'finance_admin' },
  { email: 'marketing@demo.eazyfoods.test', name: 'Zainab Idris (Marketing Manager)', role: 'marketing_manager' },
  { email: 'campaigns@demo.eazyfoods.test', name: 'Luc Fontaine (Marketing Staff)', role: 'marketing_staff' },
  { email: 'dispatch@demo.eazyfoods.test', name: 'Omar Sy (Driver Operations)', role: 'driver_operations' },
  { email: 'compliance@demo.eazyfoods.test', name: 'Ines Duarte (Compliance)', role: 'compliance_officer' },
  { email: 'content@demo.eazyfoods.test', name: 'Bola Ajayi (Content)', role: 'content_manager' },
  { email: 'chefs@demo.eazyfoods.test', name: 'Ruth Kimani (Chef Operations)', role: 'chef_operations' },
];

export const TAX: { region: string; cls: string[]; rules: [string, number][] }[] = [
  { region: 'ON', cls: ['standard', 'prepared'], rules: [['HST', 13]] }, { region: 'BC', cls: ['standard', 'prepared'], rules: [['GST', 5], ['PST', 7]] },
  { region: 'AB', cls: ['standard', 'prepared'], rules: [['GST', 5]] }, { region: 'SK', cls: ['standard', 'prepared'], rules: [['GST', 5], ['PST', 6]] },
  { region: 'MB', cls: ['standard', 'prepared'], rules: [['GST', 5], ['PST', 7]] }, { region: 'QC', cls: ['standard', 'prepared'], rules: [['GST', 5], ['QST', 9.975]] },
  { region: 'NB', cls: ['standard', 'prepared'], rules: [['HST', 15]] }, { region: 'NS', cls: ['standard', 'prepared'], rules: [['HST', 15]] },
  { region: 'NL', cls: ['standard', 'prepared'], rules: [['HST', 15]] }, { region: 'PE', cls: ['standard', 'prepared'], rules: [['HST', 15]] },
  { region: 'YT', cls: ['standard', 'prepared'], rules: [['GST', 5]] }, { region: 'NT', cls: ['standard', 'prepared'], rules: [['GST', 5]] }, { region: 'NU', cls: ['standard', 'prepared'], rules: [['GST', 5]] },
];
