import { route } from "@/lib/http";
import { aiEnabled, env } from "@/lib/env";

export const GET = route({}, async () => ({ provider: aiEnabled() ? "anthropic" : "deterministic", model: aiEnabled() ? env().AI_MODEL : null, note: aiEnabled() ? "Answers are generated by an AI model using read-only, permission-checked tools over your recorded data." : "No AI provider configured: answers come from a rule-based assistant that only reads your recorded data." }));
